name: Dynamic Preview Environments
on:
  pull_request:
    types: [opened, synchronize, closed]

jobs:
  deploy-preview:
    if: github.event.action == 'opened' || github.event.action == 'synchronize'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set Image Tag
        id: vars
        run: echo "tag=${GITHUB_SHA::7}" >> $GITHUB_OUTPUT

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/my-app:${{ steps.vars.outputs.tag }}

      - name: Configure Kubernetes Credentials
        uses: azure/k8s-set-context@v3
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.KUBECONFIG }}

      - name: Generate and Apply Custom Resource
        run: |
          cat <<EOF | kubectl apply -f -
          apiVersion: devops.orima.com/v1
          kind: PreviewEnvironment
          metadata:
            name: "pr-${{ github.event.pull_request.number }}-env"
            namespace: default
          spec:
            pr_number: ${{ github.event.pull_request.number }}
            branch_name: "${{ github.head_ref }}"
            image: "my-app"
            image_tag: ${{ steps.vars.outputs.tag }}
          EOF

  teardown-preview:
    if: github.event.action == 'closed'
    runs-on: ubuntu-latest
    steps:
      - name: Configure Kubernetes Credentials
        uses: azure/k8s-set-context@v3
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.KUBECONFIG }}

      - name: Delete Custom Resource
        run: |
          kubectl delete previewenvironment pr-${{ github.event.pull_request.number }}-env --ignore-not-found
